# cloudbuild.yaml

# Definici칩n de los pasos de la compilaci칩n
steps:
  # Paso 1: Construir la imagen Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/mi-aplicacion:${SHORT_SHA}', '.']

  # Paso 2: Ejecutar pruebas (ejemplo usando Node.js)
  - name: 'node:14'
    entrypoint: 'npm'
    args: ['test']

  # Paso 3: Etiquetar la imagen Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'gcr.io/$PROJECT_ID/mi-aplicacion:${SHORT_SHA}', 'gcr.io/$PROJECT_ID/mi-aplicacion:latest']

  # Paso 4: Subir la imagen Docker a Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/mi-aplicacion:${SHORT_SHA}']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/mi-aplicacion:latest']

# Opciones de compilaci칩n (opcional)
options:
  logging: 'CLOUD_LOGGING_ONLY'  # Configurar para guardar logs solo en Cloud Logging

# Substituciones de variables (opcional)
substitutions:
  _CUSTOM_VAR: 'valor_personalizado'

# Im치genes para publicar (opcional)
images:
  - 'gcr.io/$PROJECT_ID/mi-aplicacion:${SHORT_SHA}'
  - 'gcr.io/$PROJECT_ID/mi-aplicacion:latest'


